feat: set typscript 'Content-Type' header
nestdotland/x pull request #1
Opened 2020-09-20 12:36 UTC by maximousblk

This commit sets a custom 'Content-Type' header on '*.ts' files.
We can specify more custom formats if we need to.

I also updated the repository according to template.

2020-09-20 13:04 UTC, t8 approved these changes
If this has been tested - LGTM!

2020-09-20 17:49 UTC, maximousblk commented
I have tested that `*.ts` files now have a `application/javascript` content type. but haven't tested if everything works as expected as there is no defined test to ensure that.

2020-09-21 10:53 UTC, divy-work requested changes
Overall LGTM! Thanks

2020-09-21 10:53 UTC, divy-work commented on .github/ISSUE_TEMPLATE/bug_report.md
> +  * If yuo file something completely blank in the body, the triager may close your issue without further explanation or engagement.
```suggestion
  * If you file something completely blank in the body, the triager may close your issue without further explanation or engagement.
```

2020-09-21 10:53 UTC, divy-work commented on .prettierrc
> +}
THANKS!

2020-09-23 16:29 UTC, t8 commented
@justablob would you mind giving this a reivew?

2020-10-19 08:43 UTC, justablob approved these changes
LGTM

2020-10-19 08:44 UTC, merged